# Base image
FROM php:8.2-fpm

# Actualiza el sistema e instala nano
RUN apt-get update && apt-get install -y nano && apt-get clean && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Exponer los puertos 80 y 443 para el servidor
EXPOSE 9000

# Iniciar servicios
CMD ["php-fpm"]
