# Usa la imagen base oficial de NGINX
FROM nginx:1.27

# Actualiza el sistema e instala nano
RUN apt-get update && apt-get install -y nano && apt-get clean && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /usr/share/nginx/html

# Copiar los archivos de la aplicación al contenedor
COPY ./Docker.dev/server.dev.conf /usr/share/nginx/html/server.conf

# Exponer los puertos 80 y 443 para el servidor
EXPOSE 80 

# Comando predeterminado para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]
