# Usa la imagen base oficial de NGINX
FROM nginx:1.27

# Establecer el directorio de trabajo
WORKDIR /usr/share/nginx/html

# Copiar los archivos de la aplicación al contenedor
# COPY ./server.conf /usr/share/nginx/html

# Copiar condicionalmente server.conf si está en producción
ARG APP_ENV
RUN if [ "$APP_ENV" = "production" ]; then \
        cp /usr/share/nginx/html/server.conf /etc/nginx/conf.d/default.conf; \
    fi

RUN apt-get update && apt-get install -y nano 

# Expone el puerto 80 para acceder al servidor
EXPOSE 80 443

# Comando predeterminado para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]
